### ISSUE TITLE
iframe is not working with this app

### ISSUE THREAD

**Issue by gneerajgupta83** [pepfar-datim/dashboard-information-widget#4]
I was trying to use Information Widget in the Dashboard and used <iframe> tag to embed a pdf file. When I save the code the iFrame tag gets disappear. 
I am using this with DHIS **2.37.8**
build revision **d9a77b2**
Is there any solution to this problem?

**Comment by benguaraldi** [comment]
@gneerajgupta83 Thanks for writing!

This is expected behavior—the widget removes HTML tags that could cause problems.  See this page for a probably-mostly-complete list of tags that are removed:
https://github.com/cure53/DOMPurify/wiki/Default-TAGs-ATTRIBUTEs-allow-list-%26-blocklist

However, we'll take a look at allowing iframes and then update this ticket.

**Comment by benguaraldi** [comment]
@gneerajgupta83 We decided to allow iframes in the app.

If you like, you can download version 1.1.5 with the functionality here:
https://github.com/pepfar-datim/dashboard-information-widget/releases

We'll also be adding that version to the App Hub soon, when we've done a little more testing.

Thanks for the suggestion!
